spring:
  application:
    name: ${SPRING_APPLICATION_NAME:rhd-product-service}
  webflux:
    basePath: /product-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: false
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/product-catalouge
    username: root
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product_media

management:
  server:
    port: 9084
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus, beans
  endpoint:
    health:
      show-details: always

logging:
  level:
    jp:
      rhd:
        product: TRACE
    org:
      springframework:
        data:
          r2dbc: DEBUG

server:
  port: 8084

app:
  jwtSecret: secret